pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'tomcat:latest' }
      }
      steps {
        sh "tomcat/bin/version.sh"
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Database-node') {
      agent {
        docker { image 'mysql:latest' }
      }
      steps {
        sh 'mysqld --version'
      }
    }
  }
}
